default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  root: 'localhost'
  username: <%= ENV["USERNAME_DATABASE"] %>
  password: <%= ENV["PASSWORD_DATABASE"] %>

development:
  <<: *default
  database: api_account_current_development

test:
  <<: *default
  database: api_account_current_test

production:
  <<: *default
  database: api_account_current_production
  username: api_account_current
  password: <%= ENV["API_ACCOUNT_CURRENT_DATABASE_PASSWORD"] %>
